# Generated by Django 4.0.4 on 2022-06-14 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_rename_category_category_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image2',
        ),
    ]
