# Generated by Django 4.0.4 on 2022-06-17 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_variationmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VariationManager',
        ),
    ]
