# Generated by Django 4.0.4 on 2022-06-23 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='email',
        ),
        migrations.AddField(
            model_name='address',
            name='full_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
