# Generated by Django 4.0.4 on 2022-06-03 14:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart2',
            new_name='Cart',
        ),
        migrations.RenameModel(
            old_name='CartItem2',
            new_name='CartItem',
        ),
    ]
