# Generated by Django 4.0.4 on 2022-06-18 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_delete_variationmanager'),
        ('cart', '0003_alter_cartitem_cart_alter_cartitem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='variations',
            field=models.ManyToManyField(blank=True, to='product.variation'),
        ),
    ]
