# Generated by Django 4.0.4 on 2022-06-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_paymentmethod_alter_order_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
