# Generated by Django 4.0.4 on 2022-06-11 05:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0003_paymentmethod_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PaymentMethod',
            new_name='Payment',
        ),
    ]
