# Generated by Django 4.0.4 on 2022-06-21 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_delete_variationmanager'),
        ('order', '0007_remove_payment_payment_id_remove_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='variation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.variation'),
        ),
    ]
