# Generated by Django 4.0.4 on 2022-06-22 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_remove_order_status_orderproduct_is_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking_no',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
