# Generated by Django 4.0.4 on 2022-06-23 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_remove_order_tracking_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='order',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
